# Importing Libraries

In [190]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Training Set

# Reading Dataset

In [191]:
dataset = pd.read_csv("C:/Drive D/ArhatPersonal/ML/Kaggle/pgs3e16/train.csv")
X_train = dataset.iloc[:, 1:9].values
y_train = dataset.iloc[:, 9].values

In [192]:
print(X_train)

[['I' 1.525 1.175 ... 12.7289255 6.64795775 8.34892775]
 ['I' 1.1 0.825 ... 4.52174525 2.324659 3.40194]
 ['M' 1.3875 1.1125 ... 11.3398 5.556502 6.6621325]
 ...
 ['F' 1.4875 1.2 ... 12.303683 7.540967 8.0796075]
 ['I' 1.2125 0.9625 ... 8.97261675 2.9199985 4.2807745]
 ['I' 0.9125 0.675 ... 2.05533875 1.03475675 1.70097]]


# Encoding categorical data

In [193]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))

In [194]:
print(X_train)

[[0.0 1.0 0.0 ... 12.7289255 6.64795775 8.34892775]
 [0.0 1.0 0.0 ... 4.52174525 2.324659 3.40194]
 [0.0 0.0 1.0 ... 11.3398 5.556502 6.6621325]
 ...
 [1.0 0.0 0.0 ... 12.303683 7.540967 8.0796075]
 [0.0 1.0 0.0 ... 8.97261675 2.9199985 4.2807745]
 [0.0 1.0 0.0 ... 2.05533875 1.03475675 1.70097]]


In [195]:
print(X_train.shape)

(74051, 10)


# Feature Scaling

In [196]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train[:, 3:] = sc_X.fit_transform(X_train[:, 3:])
y_train = sc_y.fit_transform(y_train.reshape(-1, 1))

In [197]:
print(X_train)

[[0.0 1.0 0.0 ... 0.46718790293639484 0.5691861452580875
  0.4533760899970644]
 [0.0 1.0 0.0 ... -0.9936876100386933 -0.9788797061264441
  -0.9267878590422635]
 [0.0 0.0 1.0 ... 0.2199239991858617 0.17836296310527144
  -0.017224225004883933]
 ...
 [1.0 0.0 0.0 ... 0.3914948711760273 0.8889505670194828
  0.3782382245765853]
 [0.0 1.0 0.0 ... -0.20143387761351608 -0.7657034249521807
  -0.6816011403017526]
 [0.0 1.0 0.0 ... -1.4327071942488234 -1.4407616486706816
  -1.4013427985400269]]


# Training the model

In [198]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 200, random_state = 0)
regressor.fit(X_train, y_train)

C:\Users\arhat\AppData\Local\Temp\ipykernel_20040\2570373025.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor.fit(X_train, y_train)


RandomForestRegressor(n_estimators=200, random_state=0)

# Evaluating model

In [199]:
y_pred = regressor.predict(X_train)
from sklearn.metrics import r2_score
r2_score(y_train, y_pred)

0.9393339314204417

# Test Set

# Importing Test Set

In [200]:
Test_dataset = pd.read_csv("C:/Drive D/ArhatPersonal/ML/Kaggle/pgs3e16/test.csv")
X_test = Test_dataset.iloc[:, 1:].values

In [201]:
print(X_test)

[['I' 1.05 0.7625 ... 3.6570855 1.7293195 2.721552]
 ['I' 1.1625 0.8875 ... 7.030676 3.24601775 3.96893]
 ['F' 1.2875 0.9875 ... 5.556502 3.8838815 4.819415]
 ...
 ['F' 1.4875 1.1625 ... 11.396499 6.84640425 8.788345]
 ['F' 1.2375 0.95 ... 6.0951425 3.72795925 4.9611625]
 ['M' 1.6625 1.3 ... 14.911837 8.29222875 10.489315]]


# Encoding categorical data

In [202]:
X_test = np.array(ct.fit_transform(X_test))

In [203]:
print(X_test)

[[0.0 1.0 0.0 ... 3.6570855 1.7293195 2.721552]
 [0.0 1.0 0.0 ... 7.030676 3.24601775 3.96893]
 [1.0 0.0 0.0 ... 5.556502 3.8838815 4.819415]
 ...
 [1.0 0.0 0.0 ... 11.396499 6.84640425 8.788345]
 [1.0 0.0 0.0 ... 6.0951425 3.72795925 4.9611625]
 [0.0 0.0 1.0 ... 14.911837 8.29222875 10.489315]]


# Feature Scaling

In [204]:
X_test[:, 3:] = sc_X.fit_transform(X_test[:, 3:])

In [205]:
print(X_test)

[[0.0 1.0 0.0 ... -1.1535023540231488 -1.1976549312171771
  -1.1254916025344588]
 [0.0 1.0 0.0 ... -0.5523338330869708 -0.6543344424441584
  -0.7766346001087079]
 [1.0 0.0 0.0 ... -0.8150293212271494 -0.4258351714648514
  -0.5387775530002412]
 ...
 [1.0 0.0 0.0 ... 0.22564895871278923 0.6354169981945962
  0.5712220001726026]
 [1.0 0.0 0.0 ... -0.7190444313297765 -0.4816905488153487
  -0.49913471181549673]
 [0.0 0.0 1.0 ... 0.8520766612009076 1.153348679081025 1.0469360943895358]]


In [206]:
#printing shape of X_test and X_train
print(X_test.shape)


(49368, 10)


In [207]:
print(X_train.shape)

(74051, 10)


# Predicting Test Set results

In [208]:
y_pred_test = regressor.predict(X_test)

In [209]:
print(sc_y.inverse_transform(y_pred_test.reshape(-1, 1)).reshape(1, -1).flatten())

[ 8.715  7.72  11.425 ... 12.79   9.86  11.8  ]


# Creating Submission File

In [210]:
submission = pd.DataFrame({'id':Test_dataset['id'],'Age': sc_y.inverse_transform(y_pred_test.reshape(-1, 1)).reshape(1, -1).flatten()})
submission.to_csv('submission.csv',index=False)