# Importing Libraries

In [312]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Training Set

# Reading Dataset

In [313]:
dataset = pd.read_csv("C:/Drive D/ArhatPersonal/ML/Kaggle/pgs3e17/train.csv")
X_train = dataset.iloc[:, 2:8].values
y_train = dataset.iloc[:, 8].values

In [314]:
print(X_train)

[['L' 300.6 309.6 1596 36.1 140]
 ['M' 302.6 312.1 1759 29.1 200]
 ['L' 299.3 308.5 1805 26.5 25]
 ...
 ['L' 300.5 311.8 1524 38.5 214]
 ['L' 301.7 310.9 1447 46.3 42]
 ['L' 296.9 308.1 1557 39.3 229]]


In [315]:
print(y_train)

[0 0 0 ... 0 0 0]


# Encoding categorical data

In [316]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train[:, 0] = le.fit_transform(X_train[:, 0])

In [317]:
print(X_train)

[[1 300.6 309.6 1596 36.1 140]
 [2 302.6 312.1 1759 29.1 200]
 [1 299.3 308.5 1805 26.5 25]
 ...
 [1 300.5 311.8 1524 38.5 214]
 [1 301.7 310.9 1447 46.3 42]
 [1 296.9 308.1 1557 39.3 229]]


In [318]:
print(X_train.shape)

(136429, 6)


# Feature Scaling

In [319]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train[:, 1:] = sc_X.fit_transform(X_train[:, 1:])

In [320]:
print(X_train)

[[1 0.39588030247736533 -0.24623038135555111 0.5454159171575027
  -0.4997111543443894 0.5564168978957562]
 [2 1.469855585166147 1.5586048337312413 1.7203081938033757
  -1.3230276803506333 1.4944327255716774]
 [1 -0.3022036312703489 -1.0403578759937562 2.0518728853721497
  -1.628830961438667 -1.2414467718164257]
 ...
 [1 0.34218153834291404 1.342024607920818 0.026445095571595603
  -0.21743120257082024 1.7133030853627256]
 [1 0.986566707956177 0.6922839304895481 -0.5285653664022217
  0.6999786406932798 -0.9756756206415815]
 [1 -1.5909739704969053 -1.3291315104076264 0.264306722131803
  -0.12333788531296412 1.9478070422817058]]


# Training the model

In [321]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

# Evaluating model

In [322]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
accuracy_score(y_train, y_pred)

[[134259     22]
 [    39   2109]]


0.9995528809857142

# Test Set

# Importing Test Set

In [323]:
Test_dataset = pd.read_csv("C:/Drive D/ArhatPersonal/ML/Kaggle/pgs3e17/test.csv")
X_test = Test_dataset.iloc[:, 2:8].values

In [324]:
print(X_test)

[['L' 302.3 311.5 1499 38.0 60]
 ['L' 301.7 311.0 1713 28.8 17]
 ['L' 301.3 310.4 1525 37.7 96]
 ...
 ['L' 295.6 306.2 1501 41.4 187]
 ['L' 298.1 307.8 1534 40.3 69]
 ['L' 303.5 312.8 1534 36.1 92]]


# Encoding categorical data

In [325]:
X_test[:, 0] = le.transform(X_test[:, 0])

In [326]:
print(X_test)

[[1 302.3 311.5 1499 38.0 60]
 [1 301.7 311.0 1713 28.8 17]
 [1 301.3 310.4 1525 37.7 96]
 ...
 [1 295.6 306.2 1501 41.4 187]
 [1 298.1 307.8 1534 40.3 69]
 [1 303.5 312.8 1534 36.1 92]]


# Feature Scaling

In [327]:
X_test[:, 1:] = sc_X.transform(X_test[:, 1:])

In [328]:
print(X_test)

[[1 1.3087592927628238 1.1254443821103945 -0.15375310636795547
  -0.27623952585698053 -0.6942708723388051]
 [1 0.986566707956177 0.7644773390930362 1.3887435022346017
  -1.3583126743223295 -1.366515548839882]
 [1 0.7717716514184328 0.3313168874721896 0.033653023649177646
  -0.31152451982867635 -0.13146137573325253]
 ...
 [1 -2.289057904244589 -2.700806273873613 -0.1393372502127914
  0.12365707248890921 1.2911959629085612]
 [1 -0.9465888008836119 -1.54571173621805 0.09852437634741604
  -0.005721238740643564 -0.553568498187417]
 [1 1.9531444623760867 2.0639586939555348 0.09852437634741604
  -0.4997111543443894 -0.1939957642449806]]


In [329]:
#printing shape of X_test and X_train
print(X_test.shape)


(90954, 6)


In [330]:
print(X_train.shape)

(136429, 6)


# Predicting Test Set results

In [331]:
y_pred_test = classifier.predict(X_test)

In [332]:
print(y_pred_test)

[0 0 0 ... 0 0 0]


# Creating Submission File

In [333]:
submission = pd.DataFrame({'id':Test_dataset['id'],'Machine Failure': y_pred_test})
submission.to_csv('submission.csv',index=False)