# Multiple Linear Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('train.csv')
X = dataset.iloc[:, 1:-6].values
y = dataset.iloc[:, -6:-4].values

In [3]:
print(X)

[[323.3907823    9.87991785   5.87557615 ...  35.52735686   0.
    0.        ]
 [273.7237977    7.25903748   4.44146675 ...  44.7073097    0.
    0.        ]
 [521.6438224   10.9113027    8.52785922 ...  45.66011997   0.
    0.        ]
 ...
 [981.3274764   10.3630811    6.14621865 ...  66.66666667   0.
    0.        ]
 [299.1712481    9.94916085   6.58976083 ...  45.58333333   0.
    0.        ]
 [785.3940622   15.67114151   9.89616386 ...  71.12704354   0.
    0.        ]]


# Feature Scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [5]:
print(X)

[[-0.3535202   0.10920165  0.00457698 ... -0.47243016 -0.68602777
  -0.68737317]
 [-0.44508269 -0.27510523 -0.3040389  ... -0.15776632 -0.68602777
  -0.68737317]
 [ 0.0119649   0.26043644  0.57534006 ... -0.12510658 -0.68602777
  -0.68737317]
 ...
 [ 0.85940475  0.18004921  0.06281841 ...  0.59494076 -0.68602777
  -0.68737317]
 [-0.3981696   0.11935494  0.15826731 ... -0.12773861 -0.68602777
  -0.68737317]
 [ 0.49819595  0.95838467  0.86979497 ...  0.74783036 -0.68602777
  -0.68737317]]


## Training the Multiple Linear Regression model on the Training set

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X,y)

LinearRegression()

## Predicting the Test set results

In [7]:
pred = np.array(X[0])
pred = pred.reshape(1, 31)
print(pred)

[[-0.3535202   0.10920165  0.00457698 -0.14709934 -0.03398912 -0.19258545
  -0.19331154 -0.01300721 -0.92042303  0.11009715 -0.31305391 -0.01000813
  -0.01543057  0.01966298  1.03474245 -0.29523084  0.05020104  0.87608546
   1.108894   -0.5997385  -0.78960135  2.13383783 -0.45365522 -0.56119663
  -0.61706918  0.11489747 -0.91653542 -0.60572453 -0.47243016 -0.68602777
  -0.68737317]]


In [8]:
regressor.predict(pred)

array([[0.70107193, 0.85380805]])

# Test Dataset

In [9]:
Test_dataset = pd.read_csv('test.csv')
X_test = Test_dataset.iloc[:, 1:].values

In [10]:
print(X_test)

[[3.44632371e+02 7.28360348e+00 4.47396552e+00 ... 4.73040823e+01
  1.00000000e+00 1.00000000e+00]
 [1.43241020e+03 1.06638690e+01 7.07902568e+00 ... 4.31666667e+01
  0.00000000e+00 0.00000000e+00]
 [8.33526081e+01 3.93185165e+00 1.77421547e+00 ... 2.46666667e+01
  1.00000000e+00 1.00000000e+00]
 ...
 [3.78113435e+02 6.31034907e+00 3.40233377e+00 ... 5.06528704e+01
  0.00000000e+00 0.00000000e+00]
 [7.37653518e+02 9.94916085e+00 7.33794949e+00 ... 5.02500000e+01
  0.00000000e+00 0.00000000e+00]
 [7.85394062e+02 1.21705046e+01 7.56538518e+00 ... 6.91309569e+01
  0.00000000e+00 0.00000000e+00]]


In [11]:
print(X.shape)

(14838, 31)


In [12]:
print(X_test.shape)

(9893, 31)


In [13]:
X_test = sc.transform(X_test)
print(X_test)

[[-0.31436073 -0.27150305 -0.29704527 ... -0.06875601  0.81114535
   0.80943386]
 [ 1.69098854  0.22415456  0.26355559 ... -0.21057538 -0.68602777
  -0.68737317]
 [-0.79603738 -0.76297962 -0.8780231  ... -0.8447051   0.81114535
   0.80943386]
 ...
 [-0.25263744 -0.41421401 -0.52765709 ...  0.04603134 -0.68602777
  -0.68737317]
 [ 0.4101849   0.11935494  0.31927518 ...  0.03222204 -0.68602777
  -0.68737317]
 [ 0.49819595  0.44507668  0.36821864 ...  0.67940993 -0.68602777
  -0.68737317]]


In [14]:
y_pred = regressor.predict(X_test)

In [15]:
print(y_pred)

[[0.46563064 0.81134976]
 [0.87143693 0.80099151]
 [0.77331283 0.76381486]
 ...
 [0.57339811 0.83860559]
 [0.59768376 0.84687624]
 [0.46908101 0.85106596]]


In [16]:
print(y_pred[:,0])

[0.46563064 0.87143693 0.77331283 ... 0.57339811 0.59768376 0.46908101]


In [17]:
submission = pd.DataFrame({'id':Test_dataset['id'],'EC1': y_pred[:,0], 'EC2': y_pred[:,1]})
submission.to_csv('submission.csv',index=False)